curl -O https://ispip.clang.cn/chinatelecom_cidr.txt
curl -O https://ispip.clang.cn/chinatelecom_ipv6.txt
curl -O https://ispip.clang.cn/unicom_cnc_cidr.txt
curl -O https://ispip.clang.cn/unicom_cnc_ipv6.txt
curl -O https://ispip.clang.cn/cmcc_cidr.txt
curl -O https://ispip.clang.cn/cmcc_ipv6.txt
curl -O https://ispip.clang.cn/crtc_cidr.txt
curl -O https://ispip.clang.cn/crtc_ipv6.txt
curl -O https://ispip.clang.cn/cernet_cidr.txt
curl -O https://ispip.clang.cn/cernet_ipv6.txt
curl -O https://ispip.clang.cn/gwbn_cidr.txt
curl -O https://ispip.clang.cn/gwbn_ipv6.txt