on:
  schedule:
    - cron: '0  1 * * *'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/release2
        with:
          licenseKey:  ${{ secrets.MMDB_LICENSEKEY }}
